apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-array-store-deployment
  namespace: default
  labels:
    app: solar-array-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-array-store
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: solar-array-store
    spec:
      containers:
        - name: solar-array-store
          image: 975149967811.dkr.ecr.eu-west-1.amazonaws.com/solenersync-solar-array-store:1.0.1679477247 # {"$imagepolicy": "flux-system:solenersync-solar-array-store"}
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: solar-array-store-service
  namespace: default
spec:
  selector:
    app: solar-array-store
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
  type: ClusterIP
