---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: solar-array-store
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/solenersync/solar-array-store.git

