apiVersion: apps/v1
kind: Deployment
metadata:
  name: userstore-deployment
  namespace: default
  labels:
    app: userstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userstore
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: userstore
    spec:
      containers:
        - name: userstore
          image: 044135815009.dkr.ecr.eu-west-1.amazonaws.com/solenersync-userstore:1.0.1675592666 # {"$imagepolicy": "flux-system:solenersync-userstore"}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: userstore-service
  namespace: default
spec:
  selector:
    app: userstore
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
