apiVersion: apps/v1
kind: Deployment
metadata:
  name: ses-front-end-deployment
  namespace: default
  labels:
    app: ses-front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ses-front-end
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: ses-front-end
    spec:
      containers:
        - name: ses-front-end
          image: 975149967811.dkr.ecr.eu-west-1.amazonaws.com/solenersync-ses-front-end:1.0.1676208688 # {"$imagepolicy": "flux-system:solenersync-ses-front-end"}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ses-front-end-service
  namespace: default
spec:
  selector:
    app: ses-front-end
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
