---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: ses-front-end
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/solenersync/ses-front-end.git

