apiVersion: apps/v1
kind: Deployment
metadata:
  name: pv-service-deployment
  namespace: default
  labels:
    app: pv-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pv-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: pv-service
    spec:
      containers:
        - name: pv-service
          image: 975149967811.dkr.ecr.eu-west-1.amazonaws.com/solenersync-pv-service:1.0.1679434785 # {"$imagepolicy": "flux-system:solenersync-pv-service"}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pv-service-service
  namespace: default
spec:
  selector:
    app: pv-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
