apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: solenersync-pv-service
  namespace: flux-system
spec:
  interval: 1m
  image: 975149967811.dkr.ecr.eu-west-1.amazonaws.com/solenersync-pv-service
  accessFrom:
    namespaceSelectors:
      - matchLabels:
          kubernetes.io/metadata.name: flux-system
