apiVersion: apps/v1
kind: Deployment
metadata:
  name: ses-demo-deployment
  namespace: default
  labels:
    app: ses-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ses-demo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: ses-demo
    spec:
      containers:
        - name: ses-demo
          image: 975149967811.dkr.ecr.eu-west-1.amazonaws.com/solenersync-ses-demo:1.0.1680441633 # {"$imagepolicy": "flux-system:solenersync-ses-demo"}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ses-demo-service
  namespace: default
spec:
  selector:
    app: ses-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
