apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: solenersync-ses-demo
  namespace: flux-system
spec:
  interval: 1m
  image: 044135815009.dkr.ecr.eu-west-1.amazonaws.com/solenersync-ses-demo
  accessFrom:
    namespaceSelectors:
      - matchLabels:
          kubernetes.io/metadata.name: flux-system