apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-store-deployment
  namespace: default
  labels:
    app: user-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-store
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: user-store
    spec:
      containers:
        - name: user-store
          image: 975149967811.dkr.ecr.eu-west-1.amazonaws.com/solenersync-user-store:1.0.1679568285 # {"$imagepolicy": "flux-system:solenersync-user-store"}
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: user-store-service
  namespace: default
spec:
  selector:
    app: user-store
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP
