apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-update-listener
  namespace: default
  labels:
    app: pod-update-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-update-listener
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: pod-update-listener
    spec:
      containers:
        - name: pod-update-listener
          image: 975149967811.dkr.ecr.eu-west-1.amazonaws.com/solenersync-pod-update-listener:1.0.1679578844 # {"$imagepolicy": "flux-system:solenersync-pod-update-listener"}