---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: pod-update-listener
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/solenersync/pod-update-listener.git

